animal : [Cat ,Dog ,]
languages :
- Ruby
- Perl
- Python
websites :
 YAML : yaml.org
 Ruby : ruby-lang.org
 Python : python.org
number : 12.3
isSet : true
parent : ~
zhengshu : 13
iso8601 : 2018-08-13t09:32:50-07:00
e : !!str 123
f : !!str true
text1 :
text2 : null
text3 : ~